/**
 * Domain types for the database layer. These replace the types that used
 * to be generated by `@prisma/client` now that persistence goes through
 * the Supabase JS client directly against plain Postgres tables.
 */

export type UserStatus = 'active' | 'invited' | 'suspended';
export type SyncRunStatus = 'RUNNING' | 'SUCCESS' | 'FAILED';

export interface Customer {
  id: string;
  name: string;
  apiBaseUrl: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface User {
  id: string;
  customerId: string;
  externalUserId: string;
  name: string;
  email: string;
  phone: string | null;
  status: UserStatus;
  companyName: string | null;
  companyIndustry: string | null;
  companyRole: string | null;
  companyWebsite: string | null;
  companyEmployees: number | null;
  externalCreatedAt: Date;
  externalUpdatedAt: Date;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
}

export interface SyncRun {
  id: string;
  customerId: string;
  status: SyncRunStatus;
  startedAt: Date;
  completedAt: Date | null;
  recordsFetched: number | null;
  recordsCreated: number | null;
  recordsUpdated: number | null;
  recordsDeleted: number | null;
  errorCode: string | null;
  errorMessage: string | null;
}

/** Raw row shapes as returned by Postgres (snake_case), before mapping to domain types. */
export interface CustomerRow {
  id: string;
  name: string;
  api_base_url: string;
  created_at: string;
  updated_at: string;
}

export interface UserRow {
  id: string;
  customer_id: string;
  external_user_id: string;
  name: string;
  email: string;
  phone: string | null;
  status: UserStatus;
  company_name: string | null;
  company_industry: string | null;
  company_role: string | null;
  company_website: string | null;
  company_employees: number | null;
  external_created_at: string;
  external_updated_at: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface SyncRunRow {
  id: string;
  customer_id: string;
  status: SyncRunStatus;
  started_at: string;
  completed_at: string | null;
  records_fetched: number | null;
  records_created: number | null;
  records_updated: number | null;
  records_deleted: number | null;
  error_code: string | null;
  error_message: string | null;
}

export function mapCustomerRow(row: CustomerRow): Customer {
  return {
    id: row.id,
    name: row.name,
    apiBaseUrl: row.api_base_url,
    createdAt: new Date(row.created_at),
    updatedAt: new Date(row.updated_at),
  };
}

export function mapUserRow(row: UserRow): User {
  return {
    id: row.id,
    customerId: row.customer_id,
    externalUserId: row.external_user_id,
    name: row.name,
    email: row.email,
    phone: row.phone,
    status: row.status,
    companyName: row.company_name,
    companyIndustry: row.company_industry,
    companyRole: row.company_role,
    companyWebsite: row.company_website,
    companyEmployees: row.company_employees,
    externalCreatedAt: new Date(row.external_created_at),
    externalUpdatedAt: new Date(row.external_updated_at),
    createdAt: new Date(row.created_at),
    updatedAt: new Date(row.updated_at),
    deletedAt: row.deleted_at ? new Date(row.deleted_at) : null,
  };
}

export function mapSyncRunRow(row: SyncRunRow): SyncRun {
  return {
    id: row.id,
    customerId: row.customer_id,
    status: row.status,
    startedAt: new Date(row.started_at),
    completedAt: row.completed_at ? new Date(row.completed_at) : null,
    recordsFetched: row.records_fetched,
    recordsCreated: row.records_created,
    recordsUpdated: row.records_updated,
    recordsDeleted: row.records_deleted,
    errorCode: row.error_code,
    errorMessage: row.error_message,
  };
}
